project_id = "eohpjvbbrvktqyacpcmn"

[functions.register-purchase]
verify_jwt = false

[functions.redeem-reward]
verify_jwt = false

[functions.google-wallet-save]
verify_jwt = false

[functions.wallet-db-proxy]
verify_jwt = false

[functions.birthday-check]
verify_jwt = false

[functions.send-auth-email]
verify_jwt = false

[functions.send-reservation-email]
verify_jwt = false

[auth.hook.send_email]
enabled = true
uri = "pg-functions://postgres/supabase_functions/http_request"
